language: node_js
node_js:
  - "7"
cache:
  directories:
  - node_modules
script:
  - ls
  - npm run linter
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gitToken
  local_dir: build
  on:
    branch: master
notifications:
  email:
    recipients:
      - morphex.e@gmail.com