language: node_js
node_js:
  - "7"
cache:
  yarn : true
  directories:
  - node_modules
script:
  - ls
  - npm run linter
  - npm test
  - npm run build
  - sh build.sh
  - more build/static/assets/Last_build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gitToken
  local_dir: build
notifications:
  email:
    recipients:
      - morphex.e@gmail.com